### ISSUE TITLE
Issue while using set_cartesian_positions and set_all_positions.

### ISSUE THREAD

**Issue by Jay-Song** [TrossenRobotics/trossen_arm#78]
Hi,

I encountered an issue while controlling the robot using the code below:

```python
    t1 = [0.3835533, -0.0534624, 0.2266434]
    driver.set_cartesian_positions(
        goal_positions=[t1[0], t1[1], t1[2] + 0.1, 0, 0, 0],
        # goal_positions=[0.42 - 0.08, -0.03, 0.30, 0, 0, 0],
        interpolation_space=trossen_arm.InterpolationSpace.cartesian,
        goal_time=3.0,
        blocking=True,
    )

    # # need to change the interpolation space <- 
    # driver.set_cartesian_positions(
    #     goal_positions=[t1[0], t1[1], t1[2] + 0.1, 0, 0, 0],
    #     # goal_positions=[0.42 - 0.08, -0.03, 0.30, 0, 0, 0],
    #     interpolation_space=trossen_arm.InterpolationSpace.joint,
    #     goal_time=1.0,
    #     blocking=True,
    # )

    input("ready to move to release point")
    print("go to release point")

    driver.set_all_positions(
        np.array([1.1, 1.57, 1.57, -1.55, 0, 1.2, 0.011]),
        2.0,
        True,
    )
```

When I excluded the second (commented-out) portion—specifically the call that changes the interpolation space from Cartesian to joint at the same position—the robot suddenly jerked and threw an error.

Is this behavior expected, or could it be caused by an internal bug? Am I missing something in the way interpolation should be handled?

Thanks.

**Comment by Jay-Song** [comment]
@Shiming-Liang hi, any other update on this? Do I need to use the latest firmware (v.1.8.2)?  Thanks.

**Comment by Shiming-Liang** [comment]
Hi! Yes, 1.8.2 should fix this issue. Please let me know if the problem still exists. Thanks!

**Comment by Jay-Song** [comment]
> Hi! Yes, 1.8.2 should fix this issue. See [the changelog](https://docs.trossenrobotics.com/trossen_arm/main/changelog.html) for details. Please let me know if the problem still exists. Thanks!

I know it's late response but the problem was fixed.
However, I encountered another problem when running mixed_interpolation_space.py as below
```
Initializing the drivers...
Configuring the drivers...
[INFO] [trossen_arm] Connecting to the arm controller's TCP server at 192.168.1.2:50001
[INFO] [trossen_arm] Connecting to the arm controller's UDP server at 192.168.1.2:50000
[INFO] [trossen_arm] Driver version: 'v1.8.3'
[INFO] [trossen_arm] Controller firmware version: 'v1.8.3'
joint space
Traceback (most recent call last):
  File "/home/jay/trossen/trossen_arm/demos/python/mixed_interpolation_space.py", line 76, in <module>
    driver.set_gripper_external_effort(-20)
RuntimeError: [ERROR] [trossen_arm] [Driver] Error occurred: Robot input with modes different than configured modes received
Latest log on the arm controller: [ERROR] [Motor Interface] Motor 6: Position limit exceeded: 0.044021 > 0.044000 or 0.044021 < -0.004000. Setting to idle.
[ERROR] [Motor Interface] Joint 0 mode mismatch: 1 != 0
```

I am pretty sure this error occurs at 74th line `driver.set_gripper_external_effort(20)` since you set the external effort and don't set it back to 0.

**Comment by Shiming-Liang** [comment]
Hello! Thanks for the update! 

Could you share the script you used to trigger this problem? The traceback says `driver.set_gripper_external_effort(-20)` is at line 76, but the one at the main branch is at line 80. It'd help me replicate the issue. Thanks!

**Comment by Jay-Song** [comment]
> Hello! Thanks for the update!
> 
> Could you share the script you used to trigger this problem? The traceback says `driver.set_gripper_external_effort(-20)` is at line 76, but the one at the main branch is at line 80. It'd help me replicate the issue. Thanks!

This script is yours. I used `demos/python/mixed_interpolation_space.py`. I know the traceback says `driver.set_gripper_external_effort(-20)` at line 76 but I am sure that the position limit error was occurred due to 74th line 'driver.set_gripper_external_effort(20)'.

Thanks.

**Comment by Jay-Song** [comment]
I checked the viscous friction coefficient—it’s 59.54109191894531—and I haven’t changed it before. I think it is too big to set to zero. Also, I don’t believe the joint characteristics can be altered after assembly. Once the motors and gears are assembled, the joint characteristics are essentially fixed and won’t change unless the joint is disassembled. I suggest either significantly reducing the desired external effort value or adding a function to automatically set it to zero after a short sleep. 

```yaml
joint_characteristics:
  - effort_correction: 1.435317039489746
    friction_transition_velocity: 0
    friction_constant_term: -0.23000000417232513
    friction_coulomb_coef: 0.45737701654434204
    friction_viscous_coef: 0.3902771770954132
  - effort_correction: 1.311566948890686
    friction_transition_velocity: 0
    friction_constant_term: -0.07000000029802322
    friction_coulomb_coef: 0.17681163549423218
    friction_viscous_coef: 0.1574043333530426
  - effort_correction: 1.3028665781021118
    friction_transition_velocity: 0
    friction_constant_term: 0.3499999940395355
    friction_coulomb_coef: 0.13124477863311768
    friction_viscous_coef: -0.16771191358566284
  - effort_correction: 1.2635632753372192
    friction_transition_velocity: 0
    friction_constant_term: -0.029999999329447746
    friction_coulomb_coef: 0.02146981470286846
    friction_viscous_coef: 0.02759725973010063
  - effort_correction: 1.2433995008468628
    friction_transition_velocity: 0
    friction_constant_term: -0.03999999910593033
    friction_coulomb_coef: 0.05145173519849777
    friction_viscous_coef: 0.035173263400793076
  - effort_correction: 1.2000000476837158
    friction_transition_velocity: 0
    friction_constant_term: 0.019999999552965164
    friction_coulomb_coef: 0
    friction_viscous_coef: 0.02126363106071949
  - effort_correction: 1.2000000476837158
    friction_transition_velocity: 0
    friction_constant_term: 15
    friction_coulomb_coef: 0
    friction_viscous_coef: 59.54109191894531
```
